### ISSUE TITLE
Paths including terminating nulls

### ISSUE THREAD

**Issue by Herringway** [MyLittleRobo/standardpaths#11]
writablePath() appears to include a null at the end of the returned string. Nulls are illegal characters in windows paths, which makes the result more difficult to use.

Platform: Windows 10 (64-bit)
dmd 2.070.0

**Comment by FreeSlave** [comment]
For me the bug appears only when retrieving Downloads directory. It uses different algorithm than others. Should be fixed now in version 0.2.1

**Comment by Herringway** [comment]
Confirmed! thank you.
