### ISSUE TITLE
Font paths on X11

### ISSUE THREAD

**Issue by FreeSlave** [MyLittleRobo/standardpaths#8]
Font paths on X11 are determined from fonts.conf files from various locations ($XDG_CONFIG_DIR/fontconfig/fonts.conf and /etc/fonts/fonts.conf).
Each file can define many paths so it's not clear which path should be returned by writablePath function. Currently it just return the first path from $XDG_CONFIG_DIR/fontconfig/fonts.conf, but it may be not writable. 
Probably Font paths should not be present in this library at all, or at least not in StandardPath enum (i.e. make separate function for retrieving font paths). We also can just return ~/.fonts

**Comment by mleise** [comment]
Thanks. I really don't have a fonts.conf in my home directory and just use the system fonts.conf which contains ~/.fonts as an entry. Adding to your train of though, it looks like these paths are tied to the fontconfig library and the best would be to let it do the configuration file discovery and parsing itself. After all it should know best and be up to date with its latest config file syntax.

[FcConfigGetFontDirs](http://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcconfiggetfontdirs.html) will list all directories and sub-directories fontconfig uses to discover fonts.

But is that a use case for a standardpaths library? I guess what you try to provide is a place where the user can install fonts to. I.e. the first directory in the list that is writable by the current user.
[EDIT: To discover the fonts themselves one would use fontconfig anyways, or a GUI toolkit that delegates to it.]

**Comment by FreeSlave** [comment]
I've hardcoded paths as "/.fonts", "/usr/local/share/fonts", "/usr/share/fonts" on Posix. Reading of fonts.conf files can be enabled with version(fontsconf), but documentation now says user should better use fontconfig.
