### ISSUE TITLE
Roaming and Local Application data on Windows

### ISSUE THREAD

**Issue by FreeSlave** [MyLittleRobo/standardpaths#9]
Which one should be used by default as application data folder?

**Comment by r4j4h** [comment]
Maybe a use for a [Flag](http://dlang.org/phobos/std_typecons.html#.Flag) to let users decide a preference?

**Comment by FreeSlave** [comment]
It does not fit the current API nicely because it would require flag parameter which is Windows-only. And there's another flag parameter already in writablePath.

I see another solution in adding 'roaming' to StandardPath enum. There're some constants which don't work across all platforms anyway, so adding another will not hurt. That also will make writablePath overload with subfolder available for roaming directory too.
